create table if not exists public.sessions (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, case_id uuid not null references public.cases(id) on delete cascade, session_date timestamptz not null, court text, room text, status public.session_status not null default 'scheduled', notes text, outcome text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_sessions_owner on public.sessions(owner_id); create index if not exists idx_sessions_case on public.sessions(case_id); create index if not exists idx_sessions_date on public.sessions(session_date);
grant select,insert,update,delete on public.sessions to authenticated; grant all on public.sessions to service_role; alter table public.sessions enable row level security;
drop policy if exists "owner manage sessions" on public.sessions; drop policy if exists "client reads sessions" on public.sessions; drop policy if exists "employee reads sessions" on public.sessions;
create policy "owner manage sessions" on public.sessions for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "client reads sessions" on public.sessions for select to authenticated using (case_id in (select id from public.cases where client_id in (select id from public.clients where portal_user_id=auth.uid())));
create policy "employee reads sessions" on public.sessions for select to authenticated using (public.employee_can_access_case(case_id, auth.uid()));
drop trigger if exists trg_sessions_updated on public.sessions; create trigger trg_sessions_updated before update on public.sessions for each row execute function public.update_updated_at_column();

create table if not exists public.documents (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, case_id uuid references public.cases(id) on delete cascade, doc_type public.document_type not null default 'other', title text not null, description text, storage_path text, file_name text, file_size bigint, mime_type text, filed_date date, judgment_date date, court text, circuit_number text, appeal_deadline date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_documents_owner on public.documents(owner_id); create index if not exists idx_documents_case on public.documents(case_id);
grant select,insert,update,delete on public.documents to authenticated; grant all on public.documents to service_role; alter table public.documents enable row level security;
drop policy if exists "owner manage documents" on public.documents; drop policy if exists "client reads case documents" on public.documents; drop policy if exists "employee reads assigned documents" on public.documents;
create policy "owner manage documents" on public.documents for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "client reads case documents" on public.documents for select to authenticated using (case_id in (select id from public.cases where client_id in (select id from public.clients where portal_user_id=auth.uid())));
create policy "employee reads assigned documents" on public.documents for select to authenticated using (case_id is not null and public.employee_can_access_case(case_id, auth.uid()));
drop trigger if exists trg_documents_updated on public.documents; create trigger trg_documents_updated before update on public.documents for each row execute function public.update_updated_at_column();
create or replace function public.set_appeal_deadline() returns trigger language plpgsql set search_path=public as $$ begin if new.doc_type='judgment_non_final' and new.judgment_date is not null then new.appeal_deadline:=new.judgment_date + interval '30 days'; end if; return new; end $$;
drop trigger if exists trg_documents_appeal on public.documents; create trigger trg_documents_appeal before insert or update on public.documents for each row execute function public.set_appeal_deadline();

create table if not exists public.document_permissions (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, document_id uuid not null references public.documents(id) on delete cascade, employee_id uuid references public.employees(id) on delete cascade, permission public.doc_permission not null default 'view', created_at timestamptz not null default now(), unique(document_id,employee_id,permission));
grant select,insert,update,delete on public.document_permissions to authenticated; grant all on public.document_permissions to service_role; alter table public.document_permissions enable row level security;
drop policy if exists "owner manage document permissions" on public.document_permissions; drop policy if exists "employee reads own document permissions" on public.document_permissions;
create policy "owner manage document permissions" on public.document_permissions for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "employee reads own document permissions" on public.document_permissions for select to authenticated using (employee_id in (select id from public.employees where user_id=auth.uid()));
create or replace function public.has_doc_permission(_case_id uuid,_user_id uuid,_perm public.doc_permission) returns boolean language sql stable security invoker set search_path=public as $$ select public.employee_can_access_case(_case_id,_user_id) or exists(select 1 from public.employees e join public.document_permissions dp on dp.employee_id=e.id join public.documents d on d.id=dp.document_id where e.user_id=_user_id and d.case_id=_case_id and dp.permission in (_perm,'manage')) $$;
revoke all on function public.has_doc_permission(uuid,uuid,public.doc_permission) from public, anon; grant execute on function public.has_doc_permission(uuid,uuid,public.doc_permission) to authenticated, service_role;

create table if not exists public.powers_of_attorney (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, client_id uuid references public.clients(id) on delete set null, wakalah_number text not null, issuer_name text, agent_name text, issuer_id_number text, agent_id_number text, issue_date date, expiry_date date, scope text, status public.wakalah_status not null default 'active', najiz_id text, najiz_synced_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_powers_owner on public.powers_of_attorney(owner_id); create unique index if not exists uniq_powers_najiz on public.powers_of_attorney(owner_id,najiz_id) where najiz_id is not null;
grant select,insert,update,delete on public.powers_of_attorney to authenticated; grant all on public.powers_of_attorney to service_role; alter table public.powers_of_attorney enable row level security;
drop policy if exists "owner manage powers" on public.powers_of_attorney; drop policy if exists "client reads own powers" on public.powers_of_attorney;
create policy "owner manage powers" on public.powers_of_attorney for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "client reads own powers" on public.powers_of_attorney for select to authenticated using (client_id in (select id from public.clients where portal_user_id=auth.uid()));
drop trigger if exists trg_powers_updated on public.powers_of_attorney; create trigger trg_powers_updated before update on public.powers_of_attorney for each row execute function public.update_updated_at_column();

create table if not exists public.executions (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, case_id uuid references public.cases(id) on delete set null, client_id uuid references public.clients(id) on delete set null, execution_number text not null, court text, amount numeric(14,2), debtor_name text, status public.execution_status not null default 'pending', filed_date date, najiz_id text, najiz_synced_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_executions_owner on public.executions(owner_id); create unique index if not exists uniq_executions_najiz on public.executions(owner_id,najiz_id) where najiz_id is not null;
grant select,insert,update,delete on public.executions to authenticated; grant all on public.executions to service_role; alter table public.executions enable row level security;
drop policy if exists "owner manage executions" on public.executions; drop policy if exists "client reads own executions" on public.executions;
create policy "owner manage executions" on public.executions for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "client reads own executions" on public.executions for select to authenticated using (client_id in (select id from public.clients where portal_user_id=auth.uid()));
drop trigger if exists trg_executions_updated on public.executions; create trigger trg_executions_updated before update on public.executions for each row execute function public.update_updated_at_column();

create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, employee_id uuid references public.employees(id) on delete set null, case_id uuid references public.cases(id) on delete set null, title text not null, description text, due_date date, status public.task_status not null default 'todo', priority public.task_priority not null default 'medium', completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_tasks_owner on public.tasks(owner_id); create index if not exists idx_tasks_employee on public.tasks(employee_id); create index if not exists idx_tasks_case on public.tasks(case_id);
grant select,insert,update,delete on public.tasks to authenticated; grant all on public.tasks to service_role; alter table public.tasks enable row level security;
drop policy if exists "owner manage tasks" on public.tasks; drop policy if exists "employee read assigned tasks" on public.tasks; drop policy if exists "employee updates assigned tasks" on public.tasks;
create policy "owner manage tasks" on public.tasks for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "employee read assigned tasks" on public.tasks for select to authenticated using (employee_id in (select id from public.employees where user_id=auth.uid() and is_active));
create policy "employee updates assigned tasks" on public.tasks for update to authenticated using (employee_id in (select id from public.employees where user_id=auth.uid() and is_active)) with check (employee_id in (select id from public.employees where user_id=auth.uid() and is_active));
drop trigger if exists trg_tasks_updated on public.tasks; create trigger trg_tasks_updated before update on public.tasks for each row execute function public.update_updated_at_column();