/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicSystemCheckRouteImport } from './routes/api/public/system-check'
import { Route as ApiPublicNajizSyncRouteImport } from './routes/api/public/najiz-sync'
import { Route as AuthenticatedAppVerificationRouteImport } from './routes/_authenticated/app.verification'
import { Route as AuthenticatedAppTeamChatRouteImport } from './routes/_authenticated/app.team-chat'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppSystemCheckRouteImport } from './routes/_authenticated/app.system-check'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSessionsRouteImport } from './routes/_authenticated/app.sessions'
import { Route as AuthenticatedAppPreferencesTestRouteImport } from './routes/_authenticated/app.preferences-test'
import { Route as AuthenticatedAppPowersRouteImport } from './routes/_authenticated/app.powers'
import { Route as AuthenticatedAppPerformanceRouteImport } from './routes/_authenticated/app.performance'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppNajizStatusRouteImport } from './routes/_authenticated/app.najiz-status'
import { Route as AuthenticatedAppNajizRouteImport } from './routes/_authenticated/app.najiz'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/app.library'
import { Route as AuthenticatedAppLawsuitRequestsRouteImport } from './routes/_authenticated/app.lawsuit-requests'
import { Route as AuthenticatedAppInquiriesRouteImport } from './routes/_authenticated/app.inquiries'
import { Route as AuthenticatedAppGovRouteImport } from './routes/_authenticated/app.gov'
import { Route as AuthenticatedAppExecutionRouteImport } from './routes/_authenticated/app.execution'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/app.employees'
import { Route as AuthenticatedAppEmployeePortalRouteImport } from './routes/_authenticated/app.employee-portal'
import { Route as AuthenticatedAppDiagnosticsRouteImport } from './routes/_authenticated/app.diagnostics'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/app.clients'
import { Route as AuthenticatedAppClientPortalRouteImport } from './routes/_authenticated/app.client-portal'
import { Route as AuthenticatedAppChangesRouteImport } from './routes/_authenticated/app.changes'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppAuditLogRouteImport } from './routes/_authenticated/app.audit-log'
import { Route as AuthenticatedAppArchiveRouteImport } from './routes/_authenticated/app.archive'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppAiIndexRouteImport } from './routes/_authenticated/app.ai.index'
import { Route as ApiPublicCronSessionRemindersRouteImport } from './routes/api/public/cron/session-reminders'
import { Route as AuthenticatedAppAiZatcaRouteImport } from './routes/_authenticated/app.ai.zatca'
import { Route as AuthenticatedAppAiMemosRouteImport } from './routes/_authenticated/app.ai.memos'
import { Route as AuthenticatedAppAiInvoicesRouteImport } from './routes/_authenticated/app.ai.invoices'
import { Route as AuthenticatedAppAiDeadlinesRouteImport } from './routes/_authenticated/app.ai.deadlines'
import { Route as AuthenticatedAppAiContractsRouteImport } from './routes/_authenticated/app.ai.contracts'
import { Route as AuthenticatedAppAiConsultantRouteImport } from './routes/_authenticated/app.ai.consultant'
import { Route as AuthenticatedAppAiCalculatorRouteImport } from './routes/_authenticated/app.ai.calculator'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicSystemCheckRoute = ApiPublicSystemCheckRouteImport.update({
  id: '/api/public/system-check',
  path: '/api/public/system-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNajizSyncRoute = ApiPublicNajizSyncRouteImport.update({
  id: '/api/public/najiz-sync',
  path: '/api/public/najiz-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVerificationRoute =
  AuthenticatedAppVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamChatRoute =
  AuthenticatedAppTeamChatRouteImport.update({
    id: '/team-chat',
    path: '/team-chat',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSystemCheckRoute =
  AuthenticatedAppSystemCheckRouteImport.update({
    id: '/system-check',
    path: '/system-check',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSessionsRoute =
  AuthenticatedAppSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPreferencesTestRoute =
  AuthenticatedAppPreferencesTestRouteImport.update({
    id: '/preferences-test',
    path: '/preferences-test',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPowersRoute = AuthenticatedAppPowersRouteImport.update({
  id: '/powers',
  path: '/powers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerformanceRoute =
  AuthenticatedAppPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNajizStatusRoute =
  AuthenticatedAppNajizStatusRouteImport.update({
    id: '/najiz-status',
    path: '/najiz-status',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNajizRoute = AuthenticatedAppNajizRouteImport.update({
  id: '/najiz',
  path: '/najiz',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLawsuitRequestsRoute =
  AuthenticatedAppLawsuitRequestsRouteImport.update({
    id: '/lawsuit-requests',
    path: '/lawsuit-requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInquiriesRoute =
  AuthenticatedAppInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGovRoute = AuthenticatedAppGovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExecutionRoute =
  AuthenticatedAppExecutionRouteImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeePortalRoute =
  AuthenticatedAppEmployeePortalRouteImport.update({
    id: '/employee-portal',
    path: '/employee-portal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiagnosticsRoute =
  AuthenticatedAppDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientPortalRoute =
  AuthenticatedAppClientPortalRouteImport.update({
    id: '/client-portal',
    path: '/client-portal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChangesRoute = AuthenticatedAppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditLogRoute =
  AuthenticatedAppAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppArchiveRoute = AuthenticatedAppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiIndexRoute = AuthenticatedAppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppAiRoute,
} as any)
const ApiPublicCronSessionRemindersRoute =
  ApiPublicCronSessionRemindersRouteImport.update({
    id: '/api/public/cron/session-reminders',
    path: '/api/public/cron/session-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAiZatcaRoute = AuthenticatedAppAiZatcaRouteImport.update({
  id: '/zatca',
  path: '/zatca',
  getParentRoute: () => AuthenticatedAppAiRoute,
} as any)
const AuthenticatedAppAiMemosRoute = AuthenticatedAppAiMemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => AuthenticatedAppAiRoute,
} as any)
const AuthenticatedAppAiInvoicesRoute =
  AuthenticatedAppAiInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiDeadlinesRoute =
  AuthenticatedAppAiDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiContractsRoute =
  AuthenticatedAppAiContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiConsultantRoute =
  AuthenticatedAppAiConsultantRouteImport.update({
    id: '/consultant',
    path: '/consultant',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)
const AuthenticatedAppAiCalculatorRoute =
  AuthenticatedAppAiCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => AuthenticatedAppAiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/ai': typeof AuthenticatedAppAiRouteWithChildren
  '/app/archive': typeof AuthenticatedAppArchiveRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/cases': typeof AuthenticatedAppCasesRoute
  '/app/changes': typeof AuthenticatedAppChangesRoute
  '/app/client-portal': typeof AuthenticatedAppClientPortalRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/app/employee-portal': typeof AuthenticatedAppEmployeePortalRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/execution': typeof AuthenticatedAppExecutionRoute
  '/app/gov': typeof AuthenticatedAppGovRoute
  '/app/inquiries': typeof AuthenticatedAppInquiriesRoute
  '/app/lawsuit-requests': typeof AuthenticatedAppLawsuitRequestsRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/najiz': typeof AuthenticatedAppNajizRoute
  '/app/najiz-status': typeof AuthenticatedAppNajizStatusRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/app/powers': typeof AuthenticatedAppPowersRoute
  '/app/preferences-test': typeof AuthenticatedAppPreferencesTestRoute
  '/app/sessions': typeof AuthenticatedAppSessionsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/system-check': typeof AuthenticatedAppSystemCheckRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team-chat': typeof AuthenticatedAppTeamChatRoute
  '/app/verification': typeof AuthenticatedAppVerificationRoute
  '/api/public/najiz-sync': typeof ApiPublicNajizSyncRoute
  '/api/public/system-check': typeof ApiPublicSystemCheckRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/ai/calculator': typeof AuthenticatedAppAiCalculatorRoute
  '/app/ai/consultant': typeof AuthenticatedAppAiConsultantRoute
  '/app/ai/contracts': typeof AuthenticatedAppAiContractsRoute
  '/app/ai/deadlines': typeof AuthenticatedAppAiDeadlinesRoute
  '/app/ai/invoices': typeof AuthenticatedAppAiInvoicesRoute
  '/app/ai/memos': typeof AuthenticatedAppAiMemosRoute
  '/app/ai/zatca': typeof AuthenticatedAppAiZatcaRoute
  '/api/public/cron/session-reminders': typeof ApiPublicCronSessionRemindersRoute
  '/app/ai/': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/archive': typeof AuthenticatedAppArchiveRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/cases': typeof AuthenticatedAppCasesRoute
  '/app/changes': typeof AuthenticatedAppChangesRoute
  '/app/client-portal': typeof AuthenticatedAppClientPortalRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/app/employee-portal': typeof AuthenticatedAppEmployeePortalRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/execution': typeof AuthenticatedAppExecutionRoute
  '/app/gov': typeof AuthenticatedAppGovRoute
  '/app/inquiries': typeof AuthenticatedAppInquiriesRoute
  '/app/lawsuit-requests': typeof AuthenticatedAppLawsuitRequestsRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/najiz': typeof AuthenticatedAppNajizRoute
  '/app/najiz-status': typeof AuthenticatedAppNajizStatusRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/app/powers': typeof AuthenticatedAppPowersRoute
  '/app/preferences-test': typeof AuthenticatedAppPreferencesTestRoute
  '/app/sessions': typeof AuthenticatedAppSessionsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/system-check': typeof AuthenticatedAppSystemCheckRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team-chat': typeof AuthenticatedAppTeamChatRoute
  '/app/verification': typeof AuthenticatedAppVerificationRoute
  '/api/public/najiz-sync': typeof ApiPublicNajizSyncRoute
  '/api/public/system-check': typeof ApiPublicSystemCheckRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/ai/calculator': typeof AuthenticatedAppAiCalculatorRoute
  '/app/ai/consultant': typeof AuthenticatedAppAiConsultantRoute
  '/app/ai/contracts': typeof AuthenticatedAppAiContractsRoute
  '/app/ai/deadlines': typeof AuthenticatedAppAiDeadlinesRoute
  '/app/ai/invoices': typeof AuthenticatedAppAiInvoicesRoute
  '/app/ai/memos': typeof AuthenticatedAppAiMemosRoute
  '/app/ai/zatca': typeof AuthenticatedAppAiZatcaRoute
  '/api/public/cron/session-reminders': typeof ApiPublicCronSessionRemindersRoute
  '/app/ai': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRouteWithChildren
  '/_authenticated/app/archive': typeof AuthenticatedAppArchiveRoute
  '/_authenticated/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRoute
  '/_authenticated/app/changes': typeof AuthenticatedAppChangesRoute
  '/_authenticated/app/client-portal': typeof AuthenticatedAppClientPortalRoute
  '/_authenticated/app/clients': typeof AuthenticatedAppClientsRoute
  '/_authenticated/app/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/_authenticated/app/employee-portal': typeof AuthenticatedAppEmployeePortalRoute
  '/_authenticated/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/app/execution': typeof AuthenticatedAppExecutionRoute
  '/_authenticated/app/gov': typeof AuthenticatedAppGovRoute
  '/_authenticated/app/inquiries': typeof AuthenticatedAppInquiriesRoute
  '/_authenticated/app/lawsuit-requests': typeof AuthenticatedAppLawsuitRequestsRoute
  '/_authenticated/app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/najiz': typeof AuthenticatedAppNajizRoute
  '/_authenticated/app/najiz-status': typeof AuthenticatedAppNajizStatusRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/_authenticated/app/powers': typeof AuthenticatedAppPowersRoute
  '/_authenticated/app/preferences-test': typeof AuthenticatedAppPreferencesTestRoute
  '/_authenticated/app/sessions': typeof AuthenticatedAppSessionsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/system-check': typeof AuthenticatedAppSystemCheckRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/team-chat': typeof AuthenticatedAppTeamChatRoute
  '/_authenticated/app/verification': typeof AuthenticatedAppVerificationRoute
  '/api/public/najiz-sync': typeof ApiPublicNajizSyncRoute
  '/api/public/system-check': typeof ApiPublicSystemCheckRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/ai/calculator': typeof AuthenticatedAppAiCalculatorRoute
  '/_authenticated/app/ai/consultant': typeof AuthenticatedAppAiConsultantRoute
  '/_authenticated/app/ai/contracts': typeof AuthenticatedAppAiContractsRoute
  '/_authenticated/app/ai/deadlines': typeof AuthenticatedAppAiDeadlinesRoute
  '/_authenticated/app/ai/invoices': typeof AuthenticatedAppAiInvoicesRoute
  '/_authenticated/app/ai/memos': typeof AuthenticatedAppAiMemosRoute
  '/_authenticated/app/ai/zatca': typeof AuthenticatedAppAiZatcaRoute
  '/api/public/cron/session-reminders': typeof ApiPublicCronSessionRemindersRoute
  '/_authenticated/app/ai/': typeof AuthenticatedAppAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/api/ai-chat'
    | '/app/ai'
    | '/app/archive'
    | '/app/audit-log'
    | '/app/cases'
    | '/app/changes'
    | '/app/client-portal'
    | '/app/clients'
    | '/app/diagnostics'
    | '/app/employee-portal'
    | '/app/employees'
    | '/app/execution'
    | '/app/gov'
    | '/app/inquiries'
    | '/app/lawsuit-requests'
    | '/app/library'
    | '/app/messages'
    | '/app/najiz'
    | '/app/najiz-status'
    | '/app/notifications'
    | '/app/performance'
    | '/app/powers'
    | '/app/preferences-test'
    | '/app/sessions'
    | '/app/settings'
    | '/app/system-check'
    | '/app/tasks'
    | '/app/team-chat'
    | '/app/verification'
    | '/api/public/najiz-sync'
    | '/api/public/system-check'
    | '/app/'
    | '/app/ai/calculator'
    | '/app/ai/consultant'
    | '/app/ai/contracts'
    | '/app/ai/deadlines'
    | '/app/ai/invoices'
    | '/app/ai/memos'
    | '/app/ai/zatca'
    | '/api/public/cron/session-reminders'
    | '/app/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/ai-chat'
    | '/app/archive'
    | '/app/audit-log'
    | '/app/cases'
    | '/app/changes'
    | '/app/client-portal'
    | '/app/clients'
    | '/app/diagnostics'
    | '/app/employee-portal'
    | '/app/employees'
    | '/app/execution'
    | '/app/gov'
    | '/app/inquiries'
    | '/app/lawsuit-requests'
    | '/app/library'
    | '/app/messages'
    | '/app/najiz'
    | '/app/najiz-status'
    | '/app/notifications'
    | '/app/performance'
    | '/app/powers'
    | '/app/preferences-test'
    | '/app/sessions'
    | '/app/settings'
    | '/app/system-check'
    | '/app/tasks'
    | '/app/team-chat'
    | '/app/verification'
    | '/api/public/najiz-sync'
    | '/api/public/system-check'
    | '/app'
    | '/app/ai/calculator'
    | '/app/ai/consultant'
    | '/app/ai/contracts'
    | '/app/ai/deadlines'
    | '/app/ai/invoices'
    | '/app/ai/memos'
    | '/app/ai/zatca'
    | '/api/public/cron/session-reminders'
    | '/app/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/api/ai-chat'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/archive'
    | '/_authenticated/app/audit-log'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/changes'
    | '/_authenticated/app/client-portal'
    | '/_authenticated/app/clients'
    | '/_authenticated/app/diagnostics'
    | '/_authenticated/app/employee-portal'
    | '/_authenticated/app/employees'
    | '/_authenticated/app/execution'
    | '/_authenticated/app/gov'
    | '/_authenticated/app/inquiries'
    | '/_authenticated/app/lawsuit-requests'
    | '/_authenticated/app/library'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/najiz'
    | '/_authenticated/app/najiz-status'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/performance'
    | '/_authenticated/app/powers'
    | '/_authenticated/app/preferences-test'
    | '/_authenticated/app/sessions'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/system-check'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/team-chat'
    | '/_authenticated/app/verification'
    | '/api/public/najiz-sync'
    | '/api/public/system-check'
    | '/_authenticated/app/'
    | '/_authenticated/app/ai/calculator'
    | '/_authenticated/app/ai/consultant'
    | '/_authenticated/app/ai/contracts'
    | '/_authenticated/app/ai/deadlines'
    | '/_authenticated/app/ai/invoices'
    | '/_authenticated/app/ai/memos'
    | '/_authenticated/app/ai/zatca'
    | '/api/public/cron/session-reminders'
    | '/_authenticated/app/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiPublicNajizSyncRoute: typeof ApiPublicNajizSyncRoute
  ApiPublicSystemCheckRoute: typeof ApiPublicSystemCheckRoute
  ApiPublicCronSessionRemindersRoute: typeof ApiPublicCronSessionRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/system-check': {
      id: '/api/public/system-check'
      path: '/api/public/system-check'
      fullPath: '/api/public/system-check'
      preLoaderRoute: typeof ApiPublicSystemCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/najiz-sync': {
      id: '/api/public/najiz-sync'
      path: '/api/public/najiz-sync'
      fullPath: '/api/public/najiz-sync'
      preLoaderRoute: typeof ApiPublicNajizSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/verification': {
      id: '/_authenticated/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AuthenticatedAppVerificationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team-chat': {
      id: '/_authenticated/app/team-chat'
      path: '/team-chat'
      fullPath: '/app/team-chat'
      preLoaderRoute: typeof AuthenticatedAppTeamChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/system-check': {
      id: '/_authenticated/app/system-check'
      path: '/system-check'
      fullPath: '/app/system-check'
      preLoaderRoute: typeof AuthenticatedAppSystemCheckRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sessions': {
      id: '/_authenticated/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AuthenticatedAppSessionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/preferences-test': {
      id: '/_authenticated/app/preferences-test'
      path: '/preferences-test'
      fullPath: '/app/preferences-test'
      preLoaderRoute: typeof AuthenticatedAppPreferencesTestRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/powers': {
      id: '/_authenticated/app/powers'
      path: '/powers'
      fullPath: '/app/powers'
      preLoaderRoute: typeof AuthenticatedAppPowersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/performance': {
      id: '/_authenticated/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AuthenticatedAppPerformanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/najiz-status': {
      id: '/_authenticated/app/najiz-status'
      path: '/najiz-status'
      fullPath: '/app/najiz-status'
      preLoaderRoute: typeof AuthenticatedAppNajizStatusRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/najiz': {
      id: '/_authenticated/app/najiz'
      path: '/najiz'
      fullPath: '/app/najiz'
      preLoaderRoute: typeof AuthenticatedAppNajizRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/library': {
      id: '/_authenticated/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lawsuit-requests': {
      id: '/_authenticated/app/lawsuit-requests'
      path: '/lawsuit-requests'
      fullPath: '/app/lawsuit-requests'
      preLoaderRoute: typeof AuthenticatedAppLawsuitRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inquiries': {
      id: '/_authenticated/app/inquiries'
      path: '/inquiries'
      fullPath: '/app/inquiries'
      preLoaderRoute: typeof AuthenticatedAppInquiriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gov': {
      id: '/_authenticated/app/gov'
      path: '/gov'
      fullPath: '/app/gov'
      preLoaderRoute: typeof AuthenticatedAppGovRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/execution': {
      id: '/_authenticated/app/execution'
      path: '/execution'
      fullPath: '/app/execution'
      preLoaderRoute: typeof AuthenticatedAppExecutionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employees': {
      id: '/_authenticated/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employee-portal': {
      id: '/_authenticated/app/employee-portal'
      path: '/employee-portal'
      fullPath: '/app/employee-portal'
      preLoaderRoute: typeof AuthenticatedAppEmployeePortalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diagnostics': {
      id: '/_authenticated/app/diagnostics'
      path: '/diagnostics'
      fullPath: '/app/diagnostics'
      preLoaderRoute: typeof AuthenticatedAppDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients': {
      id: '/_authenticated/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/client-portal': {
      id: '/_authenticated/app/client-portal'
      path: '/client-portal'
      fullPath: '/app/client-portal'
      preLoaderRoute: typeof AuthenticatedAppClientPortalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/changes': {
      id: '/_authenticated/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AuthenticatedAppChangesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit-log': {
      id: '/_authenticated/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AuthenticatedAppAuditLogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/archive': {
      id: '/_authenticated/app/archive'
      path: '/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AuthenticatedAppArchiveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai/': {
      id: '/_authenticated/app/ai/'
      path: '/'
      fullPath: '/app/ai/'
      preLoaderRoute: typeof AuthenticatedAppAiIndexRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/api/public/cron/session-reminders': {
      id: '/api/public/cron/session-reminders'
      path: '/api/public/cron/session-reminders'
      fullPath: '/api/public/cron/session-reminders'
      preLoaderRoute: typeof ApiPublicCronSessionRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ai/zatca': {
      id: '/_authenticated/app/ai/zatca'
      path: '/zatca'
      fullPath: '/app/ai/zatca'
      preLoaderRoute: typeof AuthenticatedAppAiZatcaRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/memos': {
      id: '/_authenticated/app/ai/memos'
      path: '/memos'
      fullPath: '/app/ai/memos'
      preLoaderRoute: typeof AuthenticatedAppAiMemosRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/invoices': {
      id: '/_authenticated/app/ai/invoices'
      path: '/invoices'
      fullPath: '/app/ai/invoices'
      preLoaderRoute: typeof AuthenticatedAppAiInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/deadlines': {
      id: '/_authenticated/app/ai/deadlines'
      path: '/deadlines'
      fullPath: '/app/ai/deadlines'
      preLoaderRoute: typeof AuthenticatedAppAiDeadlinesRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/contracts': {
      id: '/_authenticated/app/ai/contracts'
      path: '/contracts'
      fullPath: '/app/ai/contracts'
      preLoaderRoute: typeof AuthenticatedAppAiContractsRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/consultant': {
      id: '/_authenticated/app/ai/consultant'
      path: '/consultant'
      fullPath: '/app/ai/consultant'
      preLoaderRoute: typeof AuthenticatedAppAiConsultantRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
    '/_authenticated/app/ai/calculator': {
      id: '/_authenticated/app/ai/calculator'
      path: '/calculator'
      fullPath: '/app/ai/calculator'
      preLoaderRoute: typeof AuthenticatedAppAiCalculatorRouteImport
      parentRoute: typeof AuthenticatedAppAiRoute
    }
  }
}

interface AuthenticatedAppAiRouteChildren {
  AuthenticatedAppAiCalculatorRoute: typeof AuthenticatedAppAiCalculatorRoute
  AuthenticatedAppAiConsultantRoute: typeof AuthenticatedAppAiConsultantRoute
  AuthenticatedAppAiContractsRoute: typeof AuthenticatedAppAiContractsRoute
  AuthenticatedAppAiDeadlinesRoute: typeof AuthenticatedAppAiDeadlinesRoute
  AuthenticatedAppAiInvoicesRoute: typeof AuthenticatedAppAiInvoicesRoute
  AuthenticatedAppAiMemosRoute: typeof AuthenticatedAppAiMemosRoute
  AuthenticatedAppAiZatcaRoute: typeof AuthenticatedAppAiZatcaRoute
  AuthenticatedAppAiIndexRoute: typeof AuthenticatedAppAiIndexRoute
}

const AuthenticatedAppAiRouteChildren: AuthenticatedAppAiRouteChildren = {
  AuthenticatedAppAiCalculatorRoute: AuthenticatedAppAiCalculatorRoute,
  AuthenticatedAppAiConsultantRoute: AuthenticatedAppAiConsultantRoute,
  AuthenticatedAppAiContractsRoute: AuthenticatedAppAiContractsRoute,
  AuthenticatedAppAiDeadlinesRoute: AuthenticatedAppAiDeadlinesRoute,
  AuthenticatedAppAiInvoicesRoute: AuthenticatedAppAiInvoicesRoute,
  AuthenticatedAppAiMemosRoute: AuthenticatedAppAiMemosRoute,
  AuthenticatedAppAiZatcaRoute: AuthenticatedAppAiZatcaRoute,
  AuthenticatedAppAiIndexRoute: AuthenticatedAppAiIndexRoute,
}

const AuthenticatedAppAiRouteWithChildren =
  AuthenticatedAppAiRoute._addFileChildren(AuthenticatedAppAiRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRouteWithChildren
  AuthenticatedAppArchiveRoute: typeof AuthenticatedAppArchiveRoute
  AuthenticatedAppAuditLogRoute: typeof AuthenticatedAppAuditLogRoute
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRoute
  AuthenticatedAppChangesRoute: typeof AuthenticatedAppChangesRoute
  AuthenticatedAppClientPortalRoute: typeof AuthenticatedAppClientPortalRoute
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRoute
  AuthenticatedAppDiagnosticsRoute: typeof AuthenticatedAppDiagnosticsRoute
  AuthenticatedAppEmployeePortalRoute: typeof AuthenticatedAppEmployeePortalRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppExecutionRoute: typeof AuthenticatedAppExecutionRoute
  AuthenticatedAppGovRoute: typeof AuthenticatedAppGovRoute
  AuthenticatedAppInquiriesRoute: typeof AuthenticatedAppInquiriesRoute
  AuthenticatedAppLawsuitRequestsRoute: typeof AuthenticatedAppLawsuitRequestsRoute
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNajizRoute: typeof AuthenticatedAppNajizRoute
  AuthenticatedAppNajizStatusRoute: typeof AuthenticatedAppNajizStatusRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPerformanceRoute: typeof AuthenticatedAppPerformanceRoute
  AuthenticatedAppPowersRoute: typeof AuthenticatedAppPowersRoute
  AuthenticatedAppPreferencesTestRoute: typeof AuthenticatedAppPreferencesTestRoute
  AuthenticatedAppSessionsRoute: typeof AuthenticatedAppSessionsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSystemCheckRoute: typeof AuthenticatedAppSystemCheckRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTeamChatRoute: typeof AuthenticatedAppTeamChatRoute
  AuthenticatedAppVerificationRoute: typeof AuthenticatedAppVerificationRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRouteWithChildren,
  AuthenticatedAppArchiveRoute: AuthenticatedAppArchiveRoute,
  AuthenticatedAppAuditLogRoute: AuthenticatedAppAuditLogRoute,
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRoute,
  AuthenticatedAppChangesRoute: AuthenticatedAppChangesRoute,
  AuthenticatedAppClientPortalRoute: AuthenticatedAppClientPortalRoute,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRoute,
  AuthenticatedAppDiagnosticsRoute: AuthenticatedAppDiagnosticsRoute,
  AuthenticatedAppEmployeePortalRoute: AuthenticatedAppEmployeePortalRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppExecutionRoute: AuthenticatedAppExecutionRoute,
  AuthenticatedAppGovRoute: AuthenticatedAppGovRoute,
  AuthenticatedAppInquiriesRoute: AuthenticatedAppInquiriesRoute,
  AuthenticatedAppLawsuitRequestsRoute: AuthenticatedAppLawsuitRequestsRoute,
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNajizRoute: AuthenticatedAppNajizRoute,
  AuthenticatedAppNajizStatusRoute: AuthenticatedAppNajizStatusRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPerformanceRoute: AuthenticatedAppPerformanceRoute,
  AuthenticatedAppPowersRoute: AuthenticatedAppPowersRoute,
  AuthenticatedAppPreferencesTestRoute: AuthenticatedAppPreferencesTestRoute,
  AuthenticatedAppSessionsRoute: AuthenticatedAppSessionsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSystemCheckRoute: AuthenticatedAppSystemCheckRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTeamChatRoute: AuthenticatedAppTeamChatRoute,
  AuthenticatedAppVerificationRoute: AuthenticatedAppVerificationRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiPublicNajizSyncRoute: ApiPublicNajizSyncRoute,
  ApiPublicSystemCheckRoute: ApiPublicSystemCheckRoute,
  ApiPublicCronSessionRemindersRoute: ApiPublicCronSessionRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
